// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import Link from "next/link";
import * as Router from "next/router";

function $$default(param) {
  var chunks = [
    "And God called the dry land Earth",
    "and the gathering together of the waters called he Seas",
    "and God saw that it was good",
    "And God said",
    "Let the earth bring forth grass",
    "the herb yielding seed",
    "and the fruit tree yielding fruit after his kind",
    "whose seed is in itself",
    "upon the earth",
    "and it was so"
  ];
  var match = React.useState(function () {
        return 0;
      });
  var setCounter = match[1];
  var counter = match[0];
  var router = Router.useRouter();
  var pageId = router.query["id"];
  var backlink = function (contents) {
    return React.createElement(Link, {
                href: "/passages/" + pageId,
                children: React.createElement("a", undefined, contents)
              });
  };
  var doneButton = counter >= chunks.length ? backlink("Return to passage") : null;
  var onClick = function (param) {
    return Curry._1(setCounter, (function (prev) {
                  return prev + 1 | 0;
                }));
  };
  return React.createElement("div", {
              className: "h-full",
              onClick: onClick
            }, backlink(React.createElement("div", undefined, "Back")), React.createElement("h1", {
                  className: "text-3xl font-semibold"
                }, "Tap through passage"), React.createElement("div", undefined, chunks.filter(function (_chunk, index) {
                        return index <= counter;
                      }).map(function (chunk) {
                      return React.createElement("span", {
                                  key: chunk
                                }, chunk);
                    })), doneButton);
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
