// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "next/router";

function $$default(param) {
  var router = Router.useRouter();
  var id = router.query["id"];
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-3xl font-semibold"
                }, "Type out passage"), React.createElement("p", undefined, "Placeholder for typing out passage"), React.createElement("p", undefined, id));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
