// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$String from "rescript/lib/es6/string.js";
import * as Js_option from "rescript/lib/es6/js_option.js";

function getChunks(str) {
  var nonEmpty = function (s) {
    return s !== "";
  };
  return str.split(/[\.,!;:]/).map(function (param) {
                  return Js_option.getWithDefault("", param);
                }).map($$String.trim).filter(nonEmpty);
}

export {
  getChunks ,
  
}
/* No side effect */
