// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "./layouts/MainLayout.mjs";

var PageComponent = {};

function $$default(props) {
  var content = React.createElement(props.Component, props.pageProps);
  return React.createElement(MainLayout.make, {
              children: content
            });
}

export {
  PageComponent ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
