// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$P(Props) {
  var children = Props.children;
  return React.createElement("p", {
              className: "mb-2"
            }, children);
}

var P = {
  make: Index$P
};

function $$default(param) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-3xl font-semibold"
                }, "Your passages"), React.createElement(Index$P, {
                  children: "Example paragraph about passages"
                }));
}

export {
  P ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
